### ISSUE TITLE
Kill should accept signal names, not just numbers

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zdaemon#11]
These three should be equivalent
```
zdaemon kill 12
zdaemon kill USR2
zdaemon kill SIGUSR2
```

**Comment by freddrake** [comment]
``zc.signalhandler`` (https://pypi.python.org/pypi/zc.signalhandler/) has code you can rip off.  Not that it's hard to write, but... why bother re-inventing?

**Comment by mgedmin** [comment]
zc.signalhandler is not on GitHub

:cry:

**Comment by mgedmin** [comment]
[Now it is](https://github.com/zopefoundation/zc.signalhandler) :)

**Comment by mgedmin** [comment]
Eh, name2signal from zc.signalhandler kind of does the opposite of what I need: converts signal numbers or names to names.

I can do getattr(signal, name2signal(arg)), I suppose, to convert it back into a number.

**Comment by freddrake** [comment]
Gosh, you closed this before I could respond to your comments.

Since you had to copy ``name2signal``, you could have modified it to return the signal number instead of the normalized name.  That would have avoided the awkward extra step.

Fortunately, that's still possible with another commit.  :-)

**Comment by mgedmin** [comment]
Instead I decided to grab the opportunity to change the output to print the name of the signal being sent, instead of the number.

(Hm, there's already another number-to-name conversion function in zdrun.py.  Perhaps something could be refactored there.  I won't object ;-)
